# Generated by Django 5.1 on 2024-08-25 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
